algo: dqn_stack_action
env: LunarLander-v2
lr: 1e-2
hidden_size: 32
n_episodes: 10000
ep_thresh: 0.15
batch_size: 128
render: False
device: cpu
discount_factor: 0.1
reset_step: 25
trained_model_path: ./algorithms/dqn/trained_models/my_dqn.pth
test: False

