algo: dqn
env: LunarLander-v2
lr: 1e-2
hidden_size: 32
n_epochs: 1000
batch_size: 128
render: False
device: cuda:0
discount_factor: 0.1
trained_model_path: ./algorithms/dqn/trained_models/my_dqn.pth
test: False

