algo: dqn_stack_action
env: LunarLander-v2
lr: 1e-2
hidden_size: 64
n_episodes: 10000
ep_thresh: 0.15
batch_size: 1000
render: False
device: cuda:0
discount_factor: 0.1
reset_step: 100
trained_model_path: ./algorithms/dqn/trained_models/my_dqn.pth
test: False

