algo: simple_pg
env: LunarLander-v2
lr: 1e-2
hidden_size: 32
n_epochs: 1000
batch_size: 5000
render: False
device: cuda:0
trained_model_path: ./algorithms/simple_pg/trained_models/my_simple_pg.pth
test: False
