algo: vanilla_pg
env: LunarLander-v2
lr: 1e-2
hidden_size: 32
n_epochs: 500
batch_size: 5000
render: False
device: cpu
render: True
trained_model_path: ./algorithms/vanilla_pg/trained_models/my_vanilla_pg.pth
test: False

